# -Denv=dev -Dapollo.cluster=DEFAULT -Dserver.port=53010
app:
  id: gateway-server
apollo:
  meta: http://114.132.248.87:8080
  bootstrap:
    enabled: true
    eagerLoad:
      enabled: true
    namespaces: application,micro_service.spring-boot-http,micro_service.spring-eureka,micro_service.spring-hystrix,micro_service.spring-ribbon,micro_service.spring-boot-redis

logging:
  config: classpath:log4j2-dev.xml
