version: '3.1'
services:
  # mysql
#  mysql:
#    container_name: mysql
#    image: docker.io/mysql:5.7
#    restart: always
#    network_mode: host
#    hostname: mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: "yueliminvc@outlook.com"
#      TZ: Asia/Shanghai
#    ports:
#      - "3306"
#    volumes:
#      - "./db:/var/lib/mysql"
#      - "./init:/docker-entrypoint-initdb.d"
  # apollo
  apollo-configservice:
    container_name: apollo-configservice
    image: apolloconfig/apollo-configservice
    # volumes:
    #   - type: volume
    #     source: logs
    #     target: /opt/logs
    ports:
      - "8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://10.0.8.12:3306/ApolloConfigDB?characterEncoding=utf8
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    restart: always
    network_mode: "host"
  apollo-adminservice:
    depends_on:
      - apollo-configservice
    container_name: apollo-adminservice
    image: apolloconfig/apollo-adminservice
    # volumes:
    #   - type: volume
    #     source: logs
    #     target: /opt/logs
    ports:
      - "8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://10.0.8.12:3306/ApolloConfigDB?characterEncoding=utf8
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    restart: always
    network_mode: "host"
  apollo-portal:
    depends_on:
      - apollo-adminservice
    container_name: apollo-portal
    image: apolloconfig/apollo-portal
    # volumes:
    #   - type: volume
    #     source: logs
    #     target: /opt/logs
    ports:
      - "8070"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://10.0.8.12:3306/ApolloPortalDB?characterEncoding=utf8
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=yueliminvc@outlook.com
      - APOLLO_PORTAL_ENVS=dev
      - DEV_META=http://10.0.8.12:8080
    restart: always
    network_mode: "host"
#volumes:
#  logs:
#    driver: local
#    driver_opts:
#      type: none
#      o: bind
#      device: /tmp/logs
