# -Denv=dev -Dapollo.cluster=DEFAULT -Dserver.port=53070
app:
  id: depository-agent-service
apollo:
  meta: http://114.132.248.87:8080
  bootstrap:
    enabled: true
    eagerLoad:
      enabled: true
    namespaces: application,micro_service.spring-boot-druid,micro_service.spring-boot-http,micro_service.spring-eureka,micro_service.spring-hystrix,micro_service.spring-feign,micro_service.spring-ribbon,micro_service.mybatis-plus,micro_service.spring-rocketmq,micro_service.spring-boot-redis

logging:
  config: classpath:log4j2-dev.xml
