# -Denv=dev -Dapollo.cluster=DEFAULT -Dserver.port=53080
app:
  id: repayment-service
apollo:
  meta: http://114.132.248.87:8080
  bootstrap:
    enabled: true
    eagerLoad:
      enabled: true
    namespaces: micro_service.spring-boot-druid,application,micro_service.spring-boot-http,micro_service.spring-eureka,micro_service.spring-feign,micro_service.spring-ribbon,micro_service.mybatis-plus,micro_service.spring-rocketmq

logging:
  config: classpath:log4j2-dev.xml
